blank_issues_enabled: false
contact_links:
  - name: Discussion
    url: https://github.com/Ravendwyr/PetEmote/discussions
    about: Start a discussion without the need to open a support ticket.
  - name: Forums
    url: https://forums.wow-petopia.com/viewtopic.php?f=3&t=20346
    about: Ask a question on the official PetEmote forum.
  - name: Twitter
    url: https://twitter.com/Ravendwyr
    about: Send a tweet on Twitter.
  - name: Discord
    url: https://top.gg/servers/299308204393889802
    about: Send a message on Discord.
  - name: Armoury
    url: https://worldofwarcraft.com/en-gb/character/eu/silvermoon/okelani
    about: Send a whisper in-game.
