blank_issues_enabled: false
contact_links:
  - name: Discussion
    url: https://github.com/Ravendwyr/PetEmote/discussions
    about: Start a discussion without the need to open a support ticket.
  - name: Forums
    url: https://forums.wow-petopia.com/viewtopic.php?f=3&t=20346
    about: Ask a question on the official PetEmote forum.
  - name: Mastodon
    url: https://gamepad.club/@ravendwyr
    about: Send a toot on Mastodon.
  - name: Discord
    url: https://discord.gg/rKWQ4HsXtt
    about: Send a message on Discord.
  - name: Azeroth
    url: https://worldofwarcraft.blizzard.com/en-gb/character/eu/argent-dawn/howlsin
    about: Send a whisper in World of Warcraft.
